### ISSUE TITLE
Returning n as a part of nthToLast instead of -1

### ISSUE THREAD

**Issue by varunu28** [wzhishen/cracking-the-coding-interview#3]
In  cracking-the-coding-interview/src/chap02/Q2.java the output of nthToLast function is n in case of k is not in the limit of size of the linked list (eg: k = 100/-199). In such a case the output should be -1 instead of n as n would be the output even when we pass the value of k equal to size of linked list. 

Kindly review this once and if you agree with me then I can open a PR for the same.

**Comment by wzhishen** [comment]
The original question doesn't specify how your implementation should handle such out-of-bound edge cases, so any rules that you and your interviewer agreed on should work. Here I assume that for those cases the output will either be the head or tail of the list.

What do you mean exactly by k = 100/-199? I think k should be an integer based on the condition.

**Comment by varunu28** [comment]
I understand that the rules are not mentioned but the example given by me for k = 100/-199 can be considered as a borderline case. It is same as when we try to find the index of a particular element in an array. If its present then we return the index else return -1. So in this case also we can look at this as returning the nth to last node if the given n is in the range or return null/-1/exception if it goes out of range.

Because if we return a head or a tail in such cases then it would create confusion when this algorithm is used as a part of an application.

**Comment by varunu28** [comment]
@wzhishen  Also your repository is really helpful. I am using it almost daily from last 1 month while preparing for my Internship interviews. Thanks a ton :)

**Comment by wzhishen** [comment]
Haha, glad this repo helps.

I don't see why returning either head or tail in out-of-bound cases is confusing, see below (index is 0 based):

if k = 0, return the tail <- this is a valid limit (reach one boundary)
if k < 0, return the tail <- this doesn't have a valid input at all, but I treat it as case 1
if k = maxLen - 1, return head <- this is another valid limit (reach another boundary)
if k > maxLen, return head <- again, this doesn't have a valid input, I treat it as case 3

Case 2 and 4 are what I chose to handle such error cases. You can feel free to choose you own, as long as you can make them sound reasonable and interviewer is fine with the assumption.

I am still confused what you meant when you say k = 100/-199, which I don't think it is a valid test case at all. It will cast to k = 0, right?

**Comment by wzhishen** [comment]
Your -1/null/exception is also a valid choice to handle such case. As long as it makes sense to the interviewer... Here I am my own interviewer, and I am fine with such assumption, so I did this.

Not all applications need to return a sentinel to represent error state. Some of them do, but the other will swallow errors and will always "treat" input as valid. It depends on the nature of the application.

**Comment by varunu28** [comment]
Your last comment settles it all up.  Would be closing the issue. Thanks for the explanation.

**Comment by wzhishen** [comment]
Interviewers love to hear about your thought process instead of seeing a single right/wrong answer. If you can discuss all above with the interviewer, I am 100% sure they will be more happy than seeing you coming up with a fast/single solution.

**Comment by wzhishen** [comment]
Good luck with interviews!!
